"""create identity and rbac

Revision ID: 20260719_0003
Revises: 20260719_0002
Create Date: 2026-07-20 16:36:27.910286
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '20260719_0003'
down_revision: str | None = '20260719_0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[a-z0-9_]+[.][a-z0-9_.]+$'", name=op.f('ck_permissions_code_format')),
    sa.CheckConstraint('char_length(btrim(code)) > 0', name=op.f('ck_permissions_code_not_blank')),
    sa.CheckConstraint('char_length(btrim(module)) > 0', name=op.f('ck_permissions_module_not_blank')),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name=op.f('ck_permissions_name_not_blank')),
    sa.CheckConstraint('code = lower(code)', name=op.f('ck_permissions_code_lowercase')),
    sa.CheckConstraint('module = lower(module)', name=op.f('ck_permissions_module_lowercase')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9][a-z0-9_-]*$'", name=op.f('ck_roles_slug_format')),
    sa.CheckConstraint('(is_system = true AND organization_id IS NULL) OR (is_system = false AND organization_id IS NOT NULL)', name=op.f('ck_roles_system_organization_consistency')),
    sa.CheckConstraint('char_length(btrim(name)) > 0', name=op.f('ck_roles_name_not_blank')),
    sa.CheckConstraint('char_length(btrim(slug)) > 0', name=op.f('ck_roles_slug_not_blank')),
    sa.CheckConstraint('slug = lower(slug)', name=op.f('ck_roles_slug_lowercase')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index('ix_roles_organization_id_name', 'roles', ['organization_id', 'name'], unique=False)
    op.create_index('uq_roles_organization_id_slug', 'roles', ['organization_id', 'slug'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.create_index('uq_roles_system_slug', 'roles', ['slug'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("position('@' in email) > 1", name=op.f('ck_users_email_format')),
    sa.CheckConstraint('char_length(btrim(email)) > 3', name=op.f('ck_users_email_not_blank')),
    sa.CheckConstraint('char_length(btrim(full_name)) > 0', name=op.f('ck_users_full_name_not_blank')),
    sa.CheckConstraint('char_length(btrim(password_hash)) > 0', name=op.f('ck_users_password_hash_not_blank')),
    sa.CheckConstraint('char_length(btrim(username)) >= 3', name=op.f('ck_users_username_minimum_length')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.CheckConstraint('username = lower(username)', name=op.f('ck_users_username_lowercase')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_organization_id_email'),
    sa.UniqueConstraint('organization_id', 'username', name='uq_users_organization_id_username')
    )
    op.create_index('ix_users_organization_id_full_name', 'users', ['organization_id', 'full_name'], unique=False)
    op.create_index('ix_users_organization_id_is_active', 'users', ['organization_id', 'is_active'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_roles_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_user_roles_site_id_sites'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles'))
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_site_id', 'user_roles', ['site_id'], unique=False)
    op.create_index('uq_user_roles_global_assignment', 'user_roles', ['user_id', 'role_id'], unique=True, postgresql_where=sa.text('site_id IS NULL'))
    op.create_index('uq_user_roles_site_assignment', 'user_roles', ['user_id', 'role_id', 'site_id'], unique=True, postgresql_where=sa.text('site_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_roles_site_assignment', table_name='user_roles', postgresql_where=sa.text('site_id IS NOT NULL'))
    op.drop_index('uq_user_roles_global_assignment', table_name='user_roles', postgresql_where=sa.text('site_id IS NULL'))
    op.drop_index('ix_user_roles_site_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_users_organization_id_is_active', table_name='users')
    op.drop_index('ix_users_organization_id_full_name', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_roles_system_slug', table_name='roles', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_index('uq_roles_organization_id_slug', table_name='roles', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index('ix_roles_organization_id_name', table_name='roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
